version: '3.8'

services:
  streamlit-app:
    build: .
    ports:
      - "8501:8501"
    environment:
      - SPLASH_URL=http://splash:8050
    depends_on:
      - splash
    volumes:
      - ./data:/app/data

  splash:
    image: scrapinghub/splash:3.5
    ports:
      - "8050:8050"
    command: --max-timeout 3600
